### PR TITLE
Fixed notification clicked event when site is open

### LINKED ISSUE #344: Getting TypeError: OneSignal.getListeners is not a function when pressing On Notification
**Description:**
My Web App used to work but since a couple of Days its not working anymore.
Problem is that when on Chrome Browser (Web and Android) I click on the Push Notification.

**Steps to Reproduce Issue:**
1. Press on the Push Notification
2. Nothing Happens
3. The following shows on the console.log
```ERROR Error: Uncaught (in promise): TypeError: OneSignal.getListeners is not a function```

**Anything else:**
I can't find the same issue here or on google so I think the problem is on my Code?
Am using Angular and the following is from my code:

```
    ngOnInit() {
      console.log('Init OneSignal');
      OneSignal.push(['init', {
        appId: '',
        // autoRegister: false,
        allowLocalhostAsSecureOrigin: true,
        notifyButton: {
          enable: false
        }
      }]);
      console.log('OneSignal Initialized');
      OneSignal.push(() => {
        console.log('Register For Push');
        OneSignal.push(['registerForPushNotifications'])
      });
      OneSignal.push(() => {
        // Occurs when the user's subscription changes to a new value.
        OneSignal.on('subscriptionChange', function (isSubscribed) {
          console.log(`The user's subscription state is now:`, isSubscribed);
          OneSignal.getUserId().then(function (userId) {
            console.log('User ID is', userId);
          });
        });
      });
      this.addListenerForNotificationOpened();
    }

    addListenerForNotificationOpened() {
      OneSignal.push(['addListenerForNotificationOpened', notificationData => {
        console.log('Received NotificationOpened:', notificationData);
        this.addListenerForNotificationOpened();

        // Actions
        const payload = notificationData.data;
        if (payload.action === 'OpenDetail') {
          this.router.navigate(['/app', 'forms', payload.item]);
        }
      }]);
    }
```

### PR DESCRIPTION
**Pull request by jkasten2**
* Issue only occurred when a tab to the site was open in the background when opening a notification
* Resolves #344

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/348)

### CODE REVIEW

File: src/libraries/WorkerMessenger.ts [hunk 1]
```diff
@@ -47,14 +47,13 @@ export class WorkerMessengerReplyBuffer {
...
+    if (this.findListenersForMessage(command).length > 0)
       this.replies[command.toString()].push(record);
-    } else {
+    else
       this.replies[command.toString()] = [record];
-    }
   }
 
-  public findListenersForMessage(command: WorkerMessengerCommand): any {
+  public findListenersForMessage(command: WorkerMessengerCommand): any[] {
```
Comment (TimBest) [inline src/libraries/WorkerMessenger.ts]: should be able to update this return type to `object[]`. not much but it is slightly more restrictive then `any[]` and matches the type definition of `replies`

Comment (jkasten2) [reply src/libraries/WorkerMessenger.ts]: There was a `WorkerMessengerReplyBufferRecord` type already but wasn't being used. Just switched to using this here

File: src/libraries/Emitter.ts [hunk 2]
```diff
@@ -102,32 +100,48 @@ export default class Emitter {
    * @example
    * me.listeners('ready');
    */
-  public listeners(event: string): (EventHandler | OnceEventHandler)[] {
+  public listeners(event: string): (EventHandler | OnceEventHandler)[] | undefined {
```
Comment (TimBest) [inline src/libraries/Emitter.ts]: no need to change anything here just want to share some thoughts 
 
Convention for return types it to use `void` over `undefined`. `type void = undefined | null` making it a little more flexible for what is returned. 

Although I have heard compelling arguments to never use `null` and only use `undefined` since then you only have one null like type

File: src/libraries/WorkerMessenger.ts [hunk 3]
```diff
@@ -24,37 +24,34 @@ export enum WorkerMessengerCommand {
...
-  command: WorkerMessengerCommand,
-  payload: WorkerMessengerPayload
+  command: WorkerMessengerCommand;
+  payload: WorkerMessengerPayload;
 }
 
-export interface WorkerMessengerReplyBufferRecord {
-  callback: Function,
-  onceListenerOnly: boolean
+export class WorkerMessengerReplyBufferRecord {
```
Comment (TimBest) [inline src/libraries/WorkerMessenger.ts]: should this be a `class`?
