### PR TITLE
Resolve bug where navigator.permissions is undefined in Firefox

### LINKED ISSUE #545: TypeError: navigator.permissions is undefined
**Description:**
When allowing the notification consent in Firefox, I got an unexpected: 
```
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: navigator.permissions is undefined'. OneSignalSDKWorker.js:1:110695
```

Unfortunately I can't show the url since the platform is private.

### PR DESCRIPTION
**Pull request by rgomezp**
- Use `Notification` to get the push permission instead of `navigator.permissions`
- Added `navigator.permissions` = undefined mock to pushsubscriptionchange test to simulate SW environment in Firefox

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/555)

Closes #545 
Fixes #545

### CODE REVIEW

File: test/support/sdk/TestEnvironment.ts [hunk 1]
```diff
@@ -253,14 +255,18 @@ export class TestEnvironment {
   }
 
   static stubNotification(config: TestEnvironmentConfig) {
-    global.window.Notification = global.Notification = {
+    global.Notification = {
```
Comment (jkasten2) [inline test/support/sdk/TestEnvironment.ts]: Was this the final thing that got `Notification` to show up in the service worker tests?

Comment (rgomezp) [reply test/support/sdk/TestEnvironment.ts]: yep. Iryna helped me out with this one

File: src/service-worker/ServiceWorker.ts [hunk 2]
```diff
@@ -873,7 +873,8 @@ export class ServiceWorker {
         If the permission is revoked, we should set the subscription state to permission revoked.
        */
       let subscriptionState: null | SubscriptionStateKind = null;
-      const pushPermission = await navigator.permissions.query({name:'push', userVisibleOnly:true});
+      const pushPermission: string = Notification["permission"];
```
Comment (jkasten2) [inline src/service-worker/ServiceWorker.ts]: Now that we have the stub working can we make this `Notification.permission` and without the `string` cast.?

```typescript
const pushPermission = Notification.permission;
```
